### ISSUE TITLE
API documentation wiki comments

### ISSUE THREAD

**Issue by tashrifbillah** [AMP-SCZ/dpdash#33]
* https://github.com/PREDICT-DPACC/dpdash/wiki/API-documentation#apiv1studiesstudyenrollment

  Should we append `?start=2021-05-20&end=2021-07-20` to `/api/v1/studies/:study/enrollment`?

* Where to write [these](https://github.com/PREDICT-DPACC/dpdash/wiki/API-documentation#post-2) parameters after `/api/v1/studies/:study/enrollment`?
 
   An example is needed for `POST` method really. Or probably a react developer knows them quite well in which case examples 
   are not required.

* Similartly, where to write [these](https://github.com/PREDICT-DPACC/dpdash/wiki/API-documentation#apiv1usersuidconfigfile) parameters after `/api/v1/users/:uid/config/file`?

* What are the differences among `URL (Express route param)`, `POST body`, and `URL`. Sorry if the question is too elementary.

**Comment by blms** [comment]
I think all of these questions could be answered with some examples. I'll include these in the doc.

1. [Express route params](https://expressjs.com/en/guide/routing.html) are URL parameters that are indicated by a colon (`:`) operator in Express routes. They go in the place of the colon-prepended keyword. Example: `/api/v1/users/:uid/config/file` will be transformed into `/api/v1/users/dpdash/config/file` for `dpdash` user ID.

2. URL params: These are the simplest kind of parameters and are just appended to the URL with `?` first, and then `&` for subsequent params. Example: `/api/v1/studies/STUDY_ID/enrollment?start=2021-05-20&end=2021-07-20`.

3. `POST` body: these go in the body of the `POST` request, not in the URL string. Since we use `application/json` as the request `Content-Type`, the body is always passed as JSON, compatible with the JavaScript Fetch API [as documented here](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#uploading_json_data). So those param names listed as "`POST` body" should be keys in the JSON body.

Example:
```js
const data = {
  varName: 'some_variable',
  assessment: 'assessment_containing_variable'
};
const res = await fetch('/api/v1/studies/STUDY_ID/enrollment', {
  method: 'POST',
  headers: {
    'Content-Type': 'application/json',
  },
  body: JSON.stringify(data),
});
const { enrollmentsList } = await res.json(); // Now enrollmentsList should be an array
```

BTW, these aren't React specific, they are just common [REST API](https://restfulapi.net/) constructions using HTTP requests. Express params are Express-specific, but the other param types will work for any kind of server.
